apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-shared-storage-claim
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 'nfs-client'
  resources:
    requests:
      storage: 200G
